package:
  name: msgcenterpy
  version: 0.1.8
source:
  url: https://files.pythonhosted.org/packages/86/b8/24eb4cb85f435d7bbc2cfb50c1c2fcb1cd225f7a5df5d953a684091c6dad/msgcenterpy-0.1.8.tar.gz
  sha256: 802aba5767298de43218b329b7a1fd3ccfe67904ecf6bab1905409caf75dae86
build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --no-build-isolation
requirements:
  host:
    - python >=3.12,<3.13
    - pip
    - setuptools >=68
    - wheel
  run:
    - python >=3.12,<3.13
    - pydantic >=2
    - jsonschema >=4.25
    - pyyaml >=6
tests:
  - python:
      imports:
        - msgcenterpy.instances.json_schema_instance
about:
  license: Apache-2.0
  summary: Backend-neutral message schema conversion without ROS extras
